version: '3.7'

services:
    todo_postgres:
        container_name: 'todo_postgres'
        image: 'postgres:13.3-alpine'
        ports:
            - '127.0.0.1:5432:5432'
        volumes:
            - './pgdata:/var/lib/postgresql/data/'
        environment:
            POSTGRES_PASSWORD: 'todo'
            POSTGRES_USER: 'imran'
            POSTGRES_DB: 'todo-app'

volumes:
    pgdata: {}
